package com.chinaex123.letfishlove.init.compat.tide;

import com.chinaex123.letfishlove.LetFishLoveMod;
import com.chinaex123.letfishlove.items.RoeItem;
import net.minecraft.world.item.Item;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;

public interface LFLTideItems {
    DeferredRegister.Items ITEMS = DeferredRegister.createItems(LetFishLoveMod.MOD_ID);

    DeferredItem<Item> TUNA_ROE = ITEMS.register("tuna_roe", () -> new RoeItem(LFLTideBlocks.TUNA_ROE_BLOCK));
    DeferredItem<Item> MACKEREL_ROE = ITEMS.register("mackerel_roe", () -> new RoeItem(LFLTideBlocks.MACKEREL_ROE_BLOCK));
    DeferredItem<Item> SNOOK_ROE = ITEMS.register("snook_roe", () -> new RoeItem(LFLTideBlocks.SNOOK_ROE_BLOCK));
    DeferredItem<Item> ANGELFISH_ROE = ITEMS.register("angelfish_roe", () -> new RoeItem(LFLTideBlocks.ANGELFISH_ROE_BLOCK));
    DeferredItem<Item> MAHI_MAHI_ROE = ITEMS.register("mahi_mahi_roe", () -> new RoeItem(LFLTideBlocks.MAHI_MAHI_ROE_BLOCK));
    DeferredItem<Item> SAILFISH_ROE = ITEMS.register("sailfish_roe", () -> new RoeItem(LFLTideBlocks.SAILFISH_ROE_BLOCK));
    DeferredItem<Item> SWORDFISH_ROE = ITEMS.register("swordfish_roe", () -> new RoeItem(LFLTideBlocks.SWORDFISH_ROE_BLOCK));
    DeferredItem<Item> MANTA_RAY_ROE = ITEMS.register("manta_ray_roe", () -> new RoeItem(LFLTideBlocks.MANTA_RAY_ROE_BLOCK));
    DeferredItem<Item> AQUATHORN_ROE = ITEMS.register("aquathorn_roe", () -> new RoeItem(LFLTideBlocks.AQUATHORN_ROE_BLOCK));
    DeferredItem<Item> RAINBOW_TROUT_ROE = ITEMS.register("rainbow_trout_roe", () -> new RoeItem(LFLTideBlocks.RAINBOW_TROUT_ROE_BLOCK));
    DeferredItem<Item> BROOK_TROUT_ROE = ITEMS.register("brook_trout_roe", () -> new RoeItem(LFLTideBlocks.BROOK_TROUT_ROE_BLOCK));
    DeferredItem<Item> LARGEMOUTH_BASS_ROE = ITEMS.register("largemouth_bass_roe", () -> new RoeItem(LFLTideBlocks.LARGEMOUTH_BASS_ROE_BLOCK));
    DeferredItem<Item> SMALLMOUTH_BASS_ROE = ITEMS.register("smallmouth_bass_roe", () -> new RoeItem(LFLTideBlocks.SMALLMOUTH_BASS_ROE_BLOCK));
    DeferredItem<Item> WHITE_CRAPPIE_ROE = ITEMS.register("white_crappie_roe", () -> new RoeItem(LFLTideBlocks.WHITE_CRAPPIE_ROE_BLOCK));
    DeferredItem<Item> BLACK_CRAPPIE_ROE = ITEMS.register("black_crappie_roe", () -> new RoeItem(LFLTideBlocks.BLACK_CRAPPIE_ROE_BLOCK));
    DeferredItem<Item> YELLOW_PERCH_ROE = ITEMS.register("yellow_perch_roe", () -> new RoeItem(LFLTideBlocks.YELLOW_PERCH_ROE_BLOCK));
    DeferredItem<Item> CARP_ROE = ITEMS.register("carp_roe", () -> new RoeItem(LFLTideBlocks.CARP_ROE_BLOCK));
    DeferredItem<Item> PIKE_ROE = ITEMS.register("pike_roe", () -> new RoeItem(LFLTideBlocks.PIKE_ROE_BLOCK));
    DeferredItem<Item> GUPPY_ROE = ITEMS.register("guppy_roe", () -> new RoeItem(LFLTideBlocks.GUPPY_ROE_BLOCK));
    DeferredItem<Item> BLUEGILL_ROE = ITEMS.register("bluegill_roe", () -> new RoeItem(LFLTideBlocks.BLUEGILL_ROE_BLOCK));
    DeferredItem<Item> CATFISH_ROE = ITEMS.register("catfish_roe", () -> new RoeItem(LFLTideBlocks.CATFISH_ROE_BLOCK));
    DeferredItem<Item> WALLEYE_ROE = ITEMS.register("walleye_roe", () -> new RoeItem(LFLTideBlocks.WALLEYE_ROE_BLOCK));
    DeferredItem<Item> ARAPAIMA_ROE = ITEMS.register("arapaima_roe", () -> new RoeItem(LFLTideBlocks.ARAPAIMA_ROE_BLOCK));
    DeferredItem<Item> MIRAGE_CATFISH_ROE = ITEMS.register("mirage_catfish_roe", () -> new RoeItem(LFLTideBlocks.MIRAGE_CATFISH_ROE_BLOCK));
    DeferredItem<Item> SAND_TIGER_SHARK_ROE = ITEMS.register("sand_tiger_shark_roe", () -> new RoeItem(LFLTideBlocks.SAND_TIGER_SHARK_ROE_BLOCK));
    DeferredItem<Item> SLIMY_SALMON_ROE = ITEMS.register("slimy_salmon_roe", () -> new RoeItem(LFLTideBlocks.SLIMY_SALMON_ROE_BLOCK));
    DeferredItem<Item> FROSTBITE_FLOUNDER_ROE = ITEMS.register("frostbite_flounder_roe", () -> new RoeItem(LFLTideBlocks.FROSTBITE_FLOUNDER_ROE_BLOCK));
    DeferredItem<Item> STURGEON_ROE = ITEMS.register("sturgeon_roe", () -> new RoeItem(LFLTideBlocks.STURGEON_ROE_BLOCK));
    DeferredItem<Item> BLOSSOM_BASS_ROE = ITEMS.register("blossom_bass_roe", () -> new RoeItem(LFLTideBlocks.BLOSSOM_BASS_ROE_BLOCK));
    DeferredItem<Item> SPORE_STALKER_ROE = ITEMS.register("spore_stalker_roe", () -> new RoeItem(LFLTideBlocks.SPORE_STALKER_ROE_BLOCK));
    DeferredItem<Item> MOONEYE_ROE = ITEMS.register("mooneye_roe", () -> new RoeItem(LFLTideBlocks.MOONEYE_ROE_BLOCK));
    DeferredItem<Item> BULL_SHARK_ROE = ITEMS.register("bull_shark_roe", () -> new RoeItem(LFLTideBlocks.BULL_SHARK_ROE_BLOCK));
    DeferredItem<Item> OCEAN_PERCH_ROE = ITEMS.register("ocean_perch_roe", () -> new RoeItem(LFLTideBlocks.OCEAN_PERCH_ROE_BLOCK));
    DeferredItem<Item> RED_SNAPPER_ROE = ITEMS.register("red_snapper_roe", () -> new RoeItem(LFLTideBlocks.RED_SNAPPER_ROE_BLOCK));
    DeferredItem<Item> FLOUNDER_ROE = ITEMS.register("flounder_roe", () -> new RoeItem(LFLTideBlocks.FLOUNDER_ROE_BLOCK));
    DeferredItem<Item> ANCHOVY_ROE = ITEMS.register("anchovy_roe", () -> new RoeItem(LFLTideBlocks.ANCHOVY_ROE_BLOCK));
    DeferredItem<Item> DEVILS_HOLE_PUPFISH_ROE = ITEMS.register("devils_hole_pupfish_roe", () -> new RoeItem(LFLTideBlocks.DEVILS_HOLE_PUPFISH_ROE_BLOCK));
    DeferredItem<Item> MIDAS_FISH_ROE = ITEMS.register("midas_fish_roe", () -> new RoeItem(LFLTideBlocks.MIDAS_FISH_ROE_BLOCK));
    DeferredItem<Item> INCANDESCENT_LARVA_ROE = ITEMS.register("incandescent_larva_roe", () -> new RoeItem(LFLTideBlocks.INCANDESCENT_LARVA_ROE_BLOCK));
    DeferredItem<Item> BEDROCK_BUG_ROE = ITEMS.register("bedrock_bug_roe", () -> new RoeItem(LFLTideBlocks.BEDROCK_BUG_ROE_BLOCK));
    DeferredItem<Item> SLEEPY_CARP_ROE = ITEMS.register("sleepy_carp_roe", () -> new RoeItem(LFLTideBlocks.SLEEPY_CARP_ROE_BLOCK));
    DeferredItem<Item> BLUE_NEONFISH_ROE = ITEMS.register("blue_neonfish_roe", () -> new RoeItem(LFLTideBlocks.BLUE_NEONFISH_ROE_BLOCK));
    DeferredItem<Item> JUDGMENT_FISH_ROE = ITEMS.register("judgment_fish_roe", () -> new RoeItem(LFLTideBlocks.JUDGMENT_FISH_ROE_BLOCK));
    DeferredItem<Item> DEEP_BLUE_ROE = ITEMS.register("deep_blue_roe", () -> new RoeItem(LFLTideBlocks.DEEP_BLUE_ROE_BLOCK));
    DeferredItem<Item> NEPHROSILU_ROE = ITEMS.register("nephrosilu_roe", () -> new RoeItem(LFLTideBlocks.NEPHROSILU_ROE_BLOCK));
    DeferredItem<Item> NEPTUNE_KOI_ROE = ITEMS.register("neptune_koi_roe", () -> new RoeItem(LFLTideBlocks.NEPTUNE_KOI_ROE_BLOCK));
    DeferredItem<Item> PLUTO_SNAIL_ROE = ITEMS.register("pluto_snail_roe", () -> new RoeItem(LFLTideBlocks.PLUTO_SNAIL_ROE_BLOCK));
    DeferredItem<Item> SUN_EMBLEM_ROE = ITEMS.register("sun_emblem_roe", () -> new RoeItem(LFLTideBlocks.SUN_EMBLEM_ROE_BLOCK));
    DeferredItem<Item> SATURN_CUTTLEFISH_ROE = ITEMS.register("saturn_cuttlefish_roe", () -> new RoeItem(LFLTideBlocks.SATURN_CUTTLEFISH_ROE_BLOCK));
    DeferredItem<Item> MARSTILUS_ROE = ITEMS.register("marstilus_roe", () -> new RoeItem(LFLTideBlocks.MARSTILUS_ROE_BLOCK));
    DeferredItem<Item> URANIAS_PISCES_ROE = ITEMS.register("uranias_pisces_roe", () -> new RoeItem(LFLTideBlocks.URANIAS_PISCES_ROE_BLOCK));
    DeferredItem<Item> GREAT_WHITE_SHARK_ROE = ITEMS.register("great_white_shark_roe", () -> new RoeItem(LFLTideBlocks.GREAT_WHITE_SHARK_ROE_BLOCK));
    DeferredItem<Item> SHOOTING_STARFISH_ROE = ITEMS.register("shooting_starfish_roe", () -> new RoeItem(LFLTideBlocks.SHOOTING_STARFISH_ROE_BLOCK));
    DeferredItem<Item> COELACANTH_ROE = ITEMS.register("coelacanth_roe", () -> new RoeItem(LFLTideBlocks.COELACANTH_ROE_BLOCK));
    DeferredItem<Item> CAVE_EEL_ROE = ITEMS.register("cave_eel_roe", () -> new RoeItem(LFLTideBlocks.CAVE_EEL_ROE_BLOCK));
    DeferredItem<Item> CAVE_CRAWLER_ROE = ITEMS.register("cave_crawler_roe", () -> new RoeItem(LFLTideBlocks.CAVE_CRAWLER_ROE_BLOCK));
    DeferredItem<Item> DEEP_GROUPER_ROE = ITEMS.register("deep_grouper_roe", () -> new RoeItem(LFLTideBlocks.DEEP_GROUPER_ROE_BLOCK));
    DeferredItem<Item> SHADOW_SNAPPER_ROE = ITEMS.register("shadow_snapper_roe", () -> new RoeItem(LFLTideBlocks.SHADOW_SNAPPER_ROE_BLOCK));
    DeferredItem<Item> GLOWFISH_ROE = ITEMS.register("glowfish_roe", () -> new RoeItem(LFLTideBlocks.GLOWFISH_ROE_BLOCK));
    DeferredItem<Item> ANGLERFISH_ROE = ITEMS.register("anglerfish_roe", () -> new RoeItem(LFLTideBlocks.ANGLERFISH_ROE_BLOCK));
    DeferredItem<Item> ABYSS_ANGLER_ROE = ITEMS.register("abyss_angler_roe", () -> new RoeItem(LFLTideBlocks.ABYSS_ANGLER_ROE_BLOCK));
    DeferredItem<Item> IRON_TETRA_ROE = ITEMS.register("iron_tetra_roe", () -> new RoeItem(LFLTideBlocks.IRON_TETRA_ROE_BLOCK));
    DeferredItem<Item> LAPIS_LANTERNFISH_ROE = ITEMS.register("lapis_lanternfish_roe", () -> new RoeItem(LFLTideBlocks.LAPIS_LANTERNFISH_ROE_BLOCK));
    DeferredItem<Item> CRYSTAL_SHRIMP_ROE = ITEMS.register("crystal_shrimp_roe", () -> new RoeItem(LFLTideBlocks.CRYSTAL_SHRIMP_ROE_BLOCK));
    DeferredItem<Item> DRIPSTONE_DARTER_ROE = ITEMS.register("dripstone_darter_roe", () -> new RoeItem(LFLTideBlocks.DRIPSTONE_DARTER_ROE_BLOCK));
    DeferredItem<Item> LUMINESCENT_JELLYFISH_ROE = ITEMS.register("luminescent_jellyfish_roe", () -> new RoeItem(LFLTideBlocks.LUMINESCENT_JELLYFISH_ROE_BLOCK));
    DeferredItem<Item> CRYSTALLINE_CARP_ROE = ITEMS.register("crystalline_carp_roe", () -> new RoeItem(LFLTideBlocks.CRYSTALLINE_CARP_ROE_BLOCK));
    DeferredItem<Item> GILDED_MINNOW_ROE = ITEMS.register("gilded_minnow_roe", () -> new RoeItem(LFLTideBlocks.GILDED_MINNOW_ROE_BLOCK));
    DeferredItem<Item> BEDROCK_TETRA_ROE = ITEMS.register("bedrock_tetra_roe", () -> new RoeItem(LFLTideBlocks.BEDROCK_TETRA_ROE_BLOCK));
    DeferredItem<Item> CHASM_EEL_ROE = ITEMS.register("chasm_eel_roe", () -> new RoeItem(LFLTideBlocks.CHASM_EEL_ROE_BLOCK));
    DeferredItem<Item> ECHO_SNAPPER_ROE = ITEMS.register("echo_snapper_roe", () -> new RoeItem(LFLTideBlocks.ECHO_SNAPPER_ROE_BLOCK));
    DeferredItem<Item> WINDBASS_ROE = ITEMS.register("windbass_roe", () -> new RoeItem(LFLTideBlocks.WINDBASS_ROE_BLOCK));
    DeferredItem<Item> SNATCHER_SQUID_ROE = ITEMS.register("snatcher_squid_roe", () -> new RoeItem(LFLTideBlocks.SNATCHER_SQUID_ROE_BLOCK));
    DeferredItem<Item> VOIDSEEKER_ROE = ITEMS.register("voidseeker_roe", () -> new RoeItem(LFLTideBlocks.VOIDSEEKER_ROE_BLOCK));
    DeferredItem<Item> DRAGON_FISH_ROE = ITEMS.register("dragon_fish_roe", () -> new RoeItem(LFLTideBlocks.DRAGON_FISH_ROE_BLOCK));
    DeferredItem<Item> VENGEANCE_ROE = ITEMS.register("vengeance_roe", () -> new RoeItem(LFLTideBlocks.VENGEANCE_ROE_BLOCK));
    DeferredItem<Item> PENTAPUS_ROE = ITEMS.register("pentapus_roe", () -> new RoeItem(LFLTideBlocks.PENTAPUS_ROE_BLOCK));
    DeferredItem<Item> DARKNESS_EATER_ROE = ITEMS.register("darkness_eater_roe", () -> new RoeItem(LFLTideBlocks.DARKNESS_EATER_ROE_BLOCK));
    DeferredItem<Item> SHADOW_SHARK_ROE = ITEMS.register("shadow_shark_roe", () -> new RoeItem(LFLTideBlocks.SHADOW_SHARK_ROE_BLOCK));
    DeferredItem<Item> ALPHA_FISH_ROE = ITEMS.register("alpha_fish_roe", () -> new RoeItem(LFLTideBlocks.ALPHA_FISH_ROE_BLOCK));
    DeferredItem<Item> MAGMA_MACKEREL_ROE = ITEMS.register("magma_mackerel_roe", () -> new RoeItem(LFLTideBlocks.MAGMA_MACKEREL_ROE_BLOCK));
    DeferredItem<Item> EMBER_KOI_ROE = ITEMS.register("ember_koi_roe", () -> new RoeItem(LFLTideBlocks.EMBER_KOI_ROE_BLOCK));
    DeferredItem<Item> ASH_PERCH_ROE = ITEMS.register("ash_perch_roe", () -> new RoeItem(LFLTideBlocks.ASH_PERCH_ROE_BLOCK));
    DeferredItem<Item> OBSIDIAN_PIKE_ROE = ITEMS.register("obsidian_pike_roe", () -> new RoeItem(LFLTideBlocks.OBSIDIAN_PIKE_ROE_BLOCK));
    DeferredItem<Item> VOLCANO_TUNA_ROE = ITEMS.register("volcano_tuna_roe", () -> new RoeItem(LFLTideBlocks.VOLCANO_TUNA_ROE_BLOCK));
    DeferredItem<Item> INFERNO_GUPPY_ROE = ITEMS.register("inferno_guppy_roe", () -> new RoeItem(LFLTideBlocks.INFERNO_GUPPY_ROE_BLOCK));
    DeferredItem<Item> WARPED_GUPPY_ROE = ITEMS.register("warped_guppy_roe", () -> new RoeItem(LFLTideBlocks.WARPED_GUPPY_ROE_BLOCK));
    DeferredItem<Item> CRIMSON_FANGJAW_ROE = ITEMS.register("crimson_fangjaw_roe", () -> new RoeItem(LFLTideBlocks.CRIMSON_FANGJAW_ROE_BLOCK));
    DeferredItem<Item> SOULSCALE_ROE = ITEMS.register("soulscale_roe", () -> new RoeItem(LFLTideBlocks.SOULSCALE_ROE_BLOCK));
    DeferredItem<Item> WITHERFIN_ROE = ITEMS.register("witherfin_roe", () -> new RoeItem(LFLTideBlocks.WITHERFIN_ROE_BLOCK));
    DeferredItem<Item> BLAZING_SWORDFISH_ROE = ITEMS.register("blazing_swordfish_roe", () -> new RoeItem(LFLTideBlocks.BLAZING_SWORDFISH_ROE_BLOCK));
    DeferredItem<Item> PALE_CLUBFISH_ROE = ITEMS.register("pale_clubfish_roe", () -> new RoeItem(LFLTideBlocks.PALE_CLUBFISH_ROE_BLOCK));
    DeferredItem<Item> AMBER_ROCKFISH_ROE = ITEMS.register("amber_rockfish_roe", () -> new RoeItem(LFLTideBlocks.AMBER_ROCKFISH_ROE_BLOCK));
    DeferredItem<Item> ENDERFIN_ROE = ITEMS.register("enderfin_roe", () -> new RoeItem(LFLTideBlocks.ENDERFIN_ROE_BLOCK));
    DeferredItem<Item> CHORUS_COD_ROE = ITEMS.register("chorus_cod_roe", () -> new RoeItem(LFLTideBlocks.CHORUS_COD_ROE_BLOCK));
    DeferredItem<Item> ENDER_GLIDER_ROE = ITEMS.register("ender_glider_roe", () -> new RoeItem(LFLTideBlocks.ENDER_GLIDER_ROE_BLOCK));
    DeferredItem<Item> ENDERGAZER_ROE = ITEMS.register("endergazer_roe", () -> new RoeItem(LFLTideBlocks.ENDERGAZER_ROE_BLOCK));
    DeferredItem<Item> VIOLET_CARP_ROE = ITEMS.register("violet_carp_roe", () -> new RoeItem(LFLTideBlocks.VIOLET_CARP_ROE_BLOCK));
    DeferredItem<Item> RED_40_ROE = ITEMS.register("red_40_roe", () -> new RoeItem(LFLTideBlocks.RED_40_ROE_BLOCK));
    DeferredItem<Item> DUTCHMAN_SOCK_ROE = ITEMS.register("dutchman_sock_roe", () -> new RoeItem(LFLTideBlocks.DUTCHMAN_SOCK_ROE_BLOCK));
    DeferredItem<Item> ELYTROUT_ROE = ITEMS.register("elytrout_roe", () -> new RoeItem(LFLTideBlocks.ELYTROUT_ROE_BLOCK));
    DeferredItem<Item> MANTYVERN_ROE = ITEMS.register("mantyvern_roe", () -> new RoeItem(LFLTideBlocks.MANTYVERN_ROE_BLOCK));
}
